
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$package\
$nodejs\
$rust\
$nix_shell\
$memory_usage\
${custom.env_production}${custom.env_other}\
$cmd_duration\
$python\
$jobs\
$time\
$line_break\
$character\
"""

command_timeout = 2000

[custom.env_production]
when = 'test "$ENV" = production'
command = 'echo " PRODUCTION "'
format = "[$output]($style) "
style = "bold fg:white bg:red"

[custom.env_other]
when = 'test -n "$ENV" && test "$ENV" != production'
command = 'echo "$ENV"'
format = "[$output]($style) "
style = "bold yellow"

[aws]
disabled = true

[package]
disabled = true
