
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$package\
$nodejs\
$rust\
$nix_shell\
$memory_usage\
$env_var\
$cmd_duration\
$python\
$jobs\
$time\
$line_break\
$character\
"""

command_timeout = 2000

[env_var.ENV]
default = ""
format = "[$env_value]($style) "

[aws]
disabled = true

[package]
disabled = true
